---
- name: install Nginx 
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      apt: 
        name: "*"
        state: latest
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: Enable nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes


